// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module dubhe::error {
    #[error]
    const ENoPermission: vector<u8> = b"No permission";
    public fun no_permission(condition: bool) { assert!(condition, ENoPermission) }

    #[error]
    const ENotLatestVersion: vector<u8> = b"Not latest version";
    public fun not_latest_version(condition: bool) { assert!(condition, ENotLatestVersion) }

    #[error]
    const EDappPaused: vector<u8> = b"Dapp is paused";
    public fun dapp_paused(condition: bool) { assert!(condition, EDappPaused) }

    #[error]
    const EInvalidPackageId: vector<u8> = b"Invalid package id";
    public fun invalid_package_id(condition: bool) { assert!(condition, EInvalidPackageId) }

    #[error]
    const EInvalidVersion: vector<u8> = b"Invalid version";
    public fun invalid_version(condition: bool) { assert!(condition, EInvalidVersion) }

    #[error]
    const EDappAlreadyInitialized: vector<u8> = b"Dapp already initialized";
    public fun dapp_already_initialized(condition: bool) { assert!(condition, EDappAlreadyInitialized) }

    #[error]
    const EInsufficientCredit: vector<u8> = b"Insufficient credit";
    public fun insufficient_credit(condition: bool) { assert!(condition, EInsufficientCredit) }

    #[error]
    const ENoPendingOwnershipTransfer: vector<u8> = b"No pending ownership transfer";
    public fun no_pending_ownership_transfer(condition: bool) { assert!(condition, ENoPendingOwnershipTransfer) }

    #[error]
    const EUserDebtLimitExceeded: vector<u8> = b"User debt limit exceeded";
    public fun user_debt_limit_exceeded(condition: bool) { assert!(condition, EUserDebtLimitExceeded) }

    #[error]
    const EDappSuspended: vector<u8> = b"Dapp is suspended";
    public fun dapp_suspended(condition: bool) { assert!(condition, EDappSuspended) }

    #[error]
    const EDappKeyMismatch: vector<u8> = b"Dapp key mismatch";
    public fun dapp_key_mismatch(condition: bool) { assert!(condition, EDappKeyMismatch) }

    #[error]
    const ENoActiveSession: vector<u8> = b"No active session";
    public fun no_active_session(condition: bool) { assert!(condition, ENoActiveSession) }

    #[error]
    const ENotCanonicalOwner: vector<u8> = b"Not canonical owner";
    public fun not_canonical_owner(condition: bool) { assert!(condition, ENotCanonicalOwner) }

    #[error]
    const EInsufficientCreditToUnsuspend: vector<u8> = b"Insufficient credit to unsuspend";
    public fun insufficient_credit_to_unsuspend(condition: bool) { assert!(condition, EInsufficientCreditToUnsuspend) }

    #[error]
    const EUserStorageAlreadyExists: vector<u8> = b"User storage already exists";
    public fun user_storage_already_exists(condition: bool) { assert!(condition, EUserStorageAlreadyExists) }

    #[error]
    const EInvalidSessionKey: vector<u8> = b"Invalid session key";
    public fun invalid_session_key(condition: bool) { assert!(condition, EInvalidSessionKey) }

    #[error]
    const EInvalidSessionDuration: vector<u8> = b"Invalid session duration";
    public fun invalid_session_duration(condition: bool) { assert!(condition, EInvalidSessionDuration) }
}
