  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::events {

  use std::ascii::{String, string};

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::region_type::RegionType;

  use numeron::connection_type::ConnectionType;

  use numeron::position::Position;

  use numeron::creature_stats::CreatureStats;

  use numeron::map_config::MapConfig;

  use numeron::extension_data::ExtensionData;

  use numeron::connection_point::ConnectionPoint;

  use numeron::requirement::Requirement;

  use numeron::region_metadata::RegionMetadata;

  use numeron::map_created::MapCreated;

  use numeron::map_updated::MapUpdated;

  use numeron::map_connected::MapConnected;
}
