// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::agent_profile {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use numeron::dapp_key;
    use numeron::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"agent_profile";
    const OFFCHAIN: bool = false;

    public struct AgentProfile has copy, drop, store {
        owner: address,
        archetype: u8,
        faction: u8,
        role: u8,
        created_at_ms: u64,
        last_seen_at_ms: u64,
    }

    public fun new(owner: address, archetype: u8, faction: u8, role: u8, created_at_ms: u64, last_seen_at_ms: u64): AgentProfile {
        AgentProfile {
            owner,
            archetype,
            faction,
            role,
            created_at_ms,
            last_seen_at_ms,
        }
    }

    public fun owner(self: &AgentProfile): address {
        self.owner
    }

    public fun archetype(self: &AgentProfile): u8 {
        self.archetype
    }

    public fun faction(self: &AgentProfile): u8 {
        self.faction
    }

    public fun role(self: &AgentProfile): u8 {
        self.role
    }

    public fun created_at_ms(self: &AgentProfile): u64 {
        self.created_at_ms
    }

    public fun last_seen_at_ms(self: &AgentProfile): u64 {
        self.last_seen_at_ms
    }

    public fun update_owner(self: &mut AgentProfile, owner: address) {
        self.owner = owner
    }

    public fun update_archetype(self: &mut AgentProfile, archetype: u8) {
        self.archetype = archetype
    }

    public fun update_faction(self: &mut AgentProfile, faction: u8) {
        self.faction = faction
    }

    public fun update_role(self: &mut AgentProfile, role: u8) {
        self.role = role
    }

    public fun update_created_at_ms(self: &mut AgentProfile, created_at_ms: u64) {
        self.created_at_ms = created_at_ms
    }

    public fun update_last_seen_at_ms(self: &mut AgentProfile, last_seen_at_ms: u64) {
        self.last_seen_at_ms = last_seen_at_ms
    }

    public fun has(user_storage: &UserStorage, agent_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, agent_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, agent_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, agent_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"owner", b"archetype", b"faction", b"role", b"created_at_ms", b"last_seen_at_ms"], ctx);
    }

    public fun get_owner(user_storage: &UserStorage, agent_id: u64): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let owner_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"owner");
        let mut owner_bcs = sui::bcs::new(owner_raw);
        let owner = sui::bcs::peel_address(&mut owner_bcs);
        owner
    }

    public(package) fun set_owner(user_storage: &mut UserStorage, agent_id: u64, owner: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&owner);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"owner", value, ctx);
    }

    public fun get_archetype(user_storage: &UserStorage, agent_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let archetype_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"archetype");
        let mut archetype_bcs = sui::bcs::new(archetype_raw);
        let archetype = sui::bcs::peel_u8(&mut archetype_bcs);
        archetype
    }

    public(package) fun set_archetype(user_storage: &mut UserStorage, agent_id: u64, archetype: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&archetype);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"archetype", value, ctx);
    }

    public fun get_faction(user_storage: &UserStorage, agent_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let faction_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"faction");
        let mut faction_bcs = sui::bcs::new(faction_raw);
        let faction = sui::bcs::peel_u8(&mut faction_bcs);
        faction
    }

    public(package) fun set_faction(user_storage: &mut UserStorage, agent_id: u64, faction: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&faction);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"faction", value, ctx);
    }

    public fun get_role(user_storage: &UserStorage, agent_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let role_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"role");
        let mut role_bcs = sui::bcs::new(role_raw);
        let role = sui::bcs::peel_u8(&mut role_bcs);
        role
    }

    public(package) fun set_role(user_storage: &mut UserStorage, agent_id: u64, role: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&role);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"role", value, ctx);
    }

    public fun get_created_at_ms(user_storage: &UserStorage, agent_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let created_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"created_at_ms");
        let mut created_at_ms_bcs = sui::bcs::new(created_at_ms_raw);
        let created_at_ms = sui::bcs::peel_u64(&mut created_at_ms_bcs);
        created_at_ms
    }

    public(package) fun set_created_at_ms(user_storage: &mut UserStorage, agent_id: u64, created_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&created_at_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"created_at_ms", value, ctx);
    }

    public fun get_last_seen_at_ms(user_storage: &UserStorage, agent_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let last_seen_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_seen_at_ms");
        let mut last_seen_at_ms_bcs = sui::bcs::new(last_seen_at_ms_raw);
        let last_seen_at_ms = sui::bcs::peel_u64(&mut last_seen_at_ms_bcs);
        last_seen_at_ms
    }

    public(package) fun set_last_seen_at_ms(user_storage: &mut UserStorage, agent_id: u64, last_seen_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&last_seen_at_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"last_seen_at_ms", value, ctx);
    }

    public fun get(user_storage: &UserStorage, agent_id: u64): (address, u8, u8, u8, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let owner_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"owner");
        let mut owner_bcs = sui::bcs::new(owner_raw);
        let owner = sui::bcs::peel_address(&mut owner_bcs);
        let archetype_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"archetype");
        let mut archetype_bcs = sui::bcs::new(archetype_raw);
        let archetype = sui::bcs::peel_u8(&mut archetype_bcs);
        let faction_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"faction");
        let mut faction_bcs = sui::bcs::new(faction_raw);
        let faction = sui::bcs::peel_u8(&mut faction_bcs);
        let role_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"role");
        let mut role_bcs = sui::bcs::new(role_raw);
        let role = sui::bcs::peel_u8(&mut role_bcs);
        let created_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"created_at_ms");
        let mut created_at_ms_bcs = sui::bcs::new(created_at_ms_raw);
        let created_at_ms = sui::bcs::peel_u64(&mut created_at_ms_bcs);
        let last_seen_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_seen_at_ms");
        let mut last_seen_at_ms_bcs = sui::bcs::new(last_seen_at_ms_raw);
        let last_seen_at_ms = sui::bcs::peel_u64(&mut last_seen_at_ms_bcs);
        (owner, archetype, faction, role, created_at_ms, last_seen_at_ms)
    }

    public(package) fun set(user_storage: &mut UserStorage, agent_id: u64, owner: address, archetype: u8, faction: u8, role: u8, created_at_ms: u64, last_seen_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"owner", b"archetype", b"faction", b"role", b"created_at_ms", b"last_seen_at_ms"];
        let value_tuple = encode(owner, archetype, faction, role, created_at_ms, last_seen_at_ms);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, agent_id: u64): AgentProfile {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let owner_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"owner");
        let mut owner_bcs = sui::bcs::new(owner_raw);
        let owner = sui::bcs::peel_address(&mut owner_bcs);
        let archetype_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"archetype");
        let mut archetype_bcs = sui::bcs::new(archetype_raw);
        let archetype = sui::bcs::peel_u8(&mut archetype_bcs);
        let faction_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"faction");
        let mut faction_bcs = sui::bcs::new(faction_raw);
        let faction = sui::bcs::peel_u8(&mut faction_bcs);
        let role_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"role");
        let mut role_bcs = sui::bcs::new(role_raw);
        let role = sui::bcs::peel_u8(&mut role_bcs);
        let created_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"created_at_ms");
        let mut created_at_ms_bcs = sui::bcs::new(created_at_ms_raw);
        let created_at_ms = sui::bcs::peel_u64(&mut created_at_ms_bcs);
        let last_seen_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_seen_at_ms");
        let mut last_seen_at_ms_bcs = sui::bcs::new(last_seen_at_ms_raw);
        let last_seen_at_ms = sui::bcs::peel_u64(&mut last_seen_at_ms_bcs);
        AgentProfile { owner, archetype, faction, role, created_at_ms, last_seen_at_ms }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, agent_id: u64, agent_profile: AgentProfile, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"owner", b"archetype", b"faction", b"role", b"created_at_ms", b"last_seen_at_ms"];
        let value_tuple = encode_struct(agent_profile);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(owner: address, archetype: u8, faction: u8, role: u8, created_at_ms: u64, last_seen_at_ms: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&owner));
        value_tuple.push_back(to_bytes(&archetype));
        value_tuple.push_back(to_bytes(&faction));
        value_tuple.push_back(to_bytes(&role));
        value_tuple.push_back(to_bytes(&created_at_ms));
        value_tuple.push_back(to_bytes(&last_seen_at_ms));
        value_tuple
    }

    public fun encode_struct(agent_profile: AgentProfile): vector<vector<u8>> {
        encode(agent_profile.owner, agent_profile.archetype, agent_profile.faction, agent_profile.role, agent_profile.created_at_ms, agent_profile.last_seen_at_ms)
    }

    public fun decode(data: vector<u8>): AgentProfile {
        let mut bcs_type = sui::bcs::new(data);
        let owner = sui::bcs::peel_address(&mut bcs_type);
        let archetype = sui::bcs::peel_u8(&mut bcs_type);
        let faction = sui::bcs::peel_u8(&mut bcs_type);
        let role = sui::bcs::peel_u8(&mut bcs_type);
        let created_at_ms = sui::bcs::peel_u64(&mut bcs_type);
        let last_seen_at_ms = sui::bcs::peel_u64(&mut bcs_type);
        AgentProfile {
            owner,
            archetype,
            faction,
            role,
            created_at_ms,
            last_seen_at_ms,
        }
    }
}