// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::extension_registry {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use numeron::dapp_key;
    use numeron::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"extension_registry";
    const OFFCHAIN: bool = false;

    public struct ExtensionRegistry has copy, drop, store {
        publisher: address,
        namespace: u64,
        schema_version: u32,
        target_kind: u8,
        enabled: bool,
    }

    public fun new(publisher: address, namespace: u64, schema_version: u32, target_kind: u8, enabled: bool): ExtensionRegistry {
        ExtensionRegistry {
            publisher,
            namespace,
            schema_version,
            target_kind,
            enabled,
        }
    }

    public fun publisher(self: &ExtensionRegistry): address {
        self.publisher
    }

    public fun namespace(self: &ExtensionRegistry): u64 {
        self.namespace
    }

    public fun schema_version(self: &ExtensionRegistry): u32 {
        self.schema_version
    }

    public fun target_kind(self: &ExtensionRegistry): u8 {
        self.target_kind
    }

    public fun enabled(self: &ExtensionRegistry): bool {
        self.enabled
    }

    public fun update_publisher(self: &mut ExtensionRegistry, publisher: address) {
        self.publisher = publisher
    }

    public fun update_namespace(self: &mut ExtensionRegistry, namespace: u64) {
        self.namespace = namespace
    }

    public fun update_schema_version(self: &mut ExtensionRegistry, schema_version: u32) {
        self.schema_version = schema_version
    }

    public fun update_target_kind(self: &mut ExtensionRegistry, target_kind: u8) {
        self.target_kind = target_kind
    }

    public fun update_enabled(self: &mut ExtensionRegistry, enabled: bool) {
        self.enabled = enabled
    }

    public fun has(user_storage: &UserStorage, extension_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, extension_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, extension_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, extension_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"publisher", b"namespace", b"schema_version", b"target_kind", b"enabled"], ctx);
    }

    public fun get_publisher(user_storage: &UserStorage, extension_id: u64): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let publisher_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"publisher");
        let mut publisher_bcs = sui::bcs::new(publisher_raw);
        let publisher = sui::bcs::peel_address(&mut publisher_bcs);
        publisher
    }

    public(package) fun set_publisher(user_storage: &mut UserStorage, extension_id: u64, publisher: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let value = to_bytes(&publisher);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"publisher", value, ctx);
    }

    public fun get_namespace(user_storage: &UserStorage, extension_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let namespace_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"namespace");
        let mut namespace_bcs = sui::bcs::new(namespace_raw);
        let namespace = sui::bcs::peel_u64(&mut namespace_bcs);
        namespace
    }

    public(package) fun set_namespace(user_storage: &mut UserStorage, extension_id: u64, namespace: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let value = to_bytes(&namespace);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"namespace", value, ctx);
    }

    public fun get_schema_version(user_storage: &UserStorage, extension_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let schema_version_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"schema_version");
        let mut schema_version_bcs = sui::bcs::new(schema_version_raw);
        let schema_version = sui::bcs::peel_u32(&mut schema_version_bcs);
        schema_version
    }

    public(package) fun set_schema_version(user_storage: &mut UserStorage, extension_id: u64, schema_version: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let value = to_bytes(&schema_version);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"schema_version", value, ctx);
    }

    public fun get_target_kind(user_storage: &UserStorage, extension_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let target_kind_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"target_kind");
        let mut target_kind_bcs = sui::bcs::new(target_kind_raw);
        let target_kind = sui::bcs::peel_u8(&mut target_kind_bcs);
        target_kind
    }

    public(package) fun set_target_kind(user_storage: &mut UserStorage, extension_id: u64, target_kind: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let value = to_bytes(&target_kind);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"target_kind", value, ctx);
    }

    public fun get_enabled(user_storage: &UserStorage, extension_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let enabled_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"enabled");
        let mut enabled_bcs = sui::bcs::new(enabled_raw);
        let enabled = sui::bcs::peel_bool(&mut enabled_bcs);
        enabled
    }

    public(package) fun set_enabled(user_storage: &mut UserStorage, extension_id: u64, enabled: bool, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let value = to_bytes(&enabled);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"enabled", value, ctx);
    }

    public fun get(user_storage: &UserStorage, extension_id: u64): (address, u64, u32, u8, bool) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let publisher_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"publisher");
        let mut publisher_bcs = sui::bcs::new(publisher_raw);
        let publisher = sui::bcs::peel_address(&mut publisher_bcs);
        let namespace_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"namespace");
        let mut namespace_bcs = sui::bcs::new(namespace_raw);
        let namespace = sui::bcs::peel_u64(&mut namespace_bcs);
        let schema_version_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"schema_version");
        let mut schema_version_bcs = sui::bcs::new(schema_version_raw);
        let schema_version = sui::bcs::peel_u32(&mut schema_version_bcs);
        let target_kind_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"target_kind");
        let mut target_kind_bcs = sui::bcs::new(target_kind_raw);
        let target_kind = sui::bcs::peel_u8(&mut target_kind_bcs);
        let enabled_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"enabled");
        let mut enabled_bcs = sui::bcs::new(enabled_raw);
        let enabled = sui::bcs::peel_bool(&mut enabled_bcs);
        (publisher, namespace, schema_version, target_kind, enabled)
    }

    public(package) fun set(user_storage: &mut UserStorage, extension_id: u64, publisher: address, namespace: u64, schema_version: u32, target_kind: u8, enabled: bool, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let field_names = vector[b"publisher", b"namespace", b"schema_version", b"target_kind", b"enabled"];
        let value_tuple = encode(publisher, namespace, schema_version, target_kind, enabled);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, extension_id: u64): ExtensionRegistry {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let publisher_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"publisher");
        let mut publisher_bcs = sui::bcs::new(publisher_raw);
        let publisher = sui::bcs::peel_address(&mut publisher_bcs);
        let namespace_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"namespace");
        let mut namespace_bcs = sui::bcs::new(namespace_raw);
        let namespace = sui::bcs::peel_u64(&mut namespace_bcs);
        let schema_version_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"schema_version");
        let mut schema_version_bcs = sui::bcs::new(schema_version_raw);
        let schema_version = sui::bcs::peel_u32(&mut schema_version_bcs);
        let target_kind_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"target_kind");
        let mut target_kind_bcs = sui::bcs::new(target_kind_raw);
        let target_kind = sui::bcs::peel_u8(&mut target_kind_bcs);
        let enabled_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"enabled");
        let mut enabled_bcs = sui::bcs::new(enabled_raw);
        let enabled = sui::bcs::peel_bool(&mut enabled_bcs);
        ExtensionRegistry { publisher, namespace, schema_version, target_kind, enabled }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, extension_id: u64, extension_registry: ExtensionRegistry, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&extension_id));
        let field_names = vector[b"publisher", b"namespace", b"schema_version", b"target_kind", b"enabled"];
        let value_tuple = encode_struct(extension_registry);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(publisher: address, namespace: u64, schema_version: u32, target_kind: u8, enabled: bool): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&publisher));
        value_tuple.push_back(to_bytes(&namespace));
        value_tuple.push_back(to_bytes(&schema_version));
        value_tuple.push_back(to_bytes(&target_kind));
        value_tuple.push_back(to_bytes(&enabled));
        value_tuple
    }

    public fun encode_struct(extension_registry: ExtensionRegistry): vector<vector<u8>> {
        encode(extension_registry.publisher, extension_registry.namespace, extension_registry.schema_version, extension_registry.target_kind, extension_registry.enabled)
    }

    public fun decode(data: vector<u8>): ExtensionRegistry {
        let mut bcs_type = sui::bcs::new(data);
        let publisher = sui::bcs::peel_address(&mut bcs_type);
        let namespace = sui::bcs::peel_u64(&mut bcs_type);
        let schema_version = sui::bcs::peel_u32(&mut bcs_type);
        let target_kind = sui::bcs::peel_u8(&mut bcs_type);
        let enabled = sui::bcs::peel_bool(&mut bcs_type);
        ExtensionRegistry {
            publisher,
            namespace,
            schema_version,
            target_kind,
            enabled,
        }
    }
}