// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::match_participation {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use numeron::dapp_key;
    use numeron::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"match_participation";
    const OFFCHAIN: bool = false;

    public struct MatchParticipation has copy, drop, store {
        participation_id: u64,
        battle_instance_id: u64,
        team: u8,
        placement: u8,
    }

    public fun new(participation_id: u64, battle_instance_id: u64, team: u8, placement: u8): MatchParticipation {
        MatchParticipation {
            participation_id,
            battle_instance_id,
            team,
            placement,
        }
    }

    public fun participation_id(self: &MatchParticipation): u64 {
        self.participation_id
    }

    public fun battle_instance_id(self: &MatchParticipation): u64 {
        self.battle_instance_id
    }

    public fun team(self: &MatchParticipation): u8 {
        self.team
    }

    public fun placement(self: &MatchParticipation): u8 {
        self.placement
    }

    public fun update_participation_id(self: &mut MatchParticipation, participation_id: u64) {
        self.participation_id = participation_id
    }

    public fun update_battle_instance_id(self: &mut MatchParticipation, battle_instance_id: u64) {
        self.battle_instance_id = battle_instance_id
    }

    public fun update_team(self: &mut MatchParticipation, team: u8) {
        self.team = team
    }

    public fun update_placement(self: &mut MatchParticipation, placement: u8) {
        self.placement = placement
    }

    public fun has(user_storage: &UserStorage, match_id: u64, agent_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, match_id: u64, agent_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, match_id: u64, agent_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"participation_id", b"battle_instance_id", b"team", b"placement"], ctx);
    }

    public fun get_participation_id(user_storage: &UserStorage, match_id: u64, agent_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let participation_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"participation_id");
        let mut participation_id_bcs = sui::bcs::new(participation_id_raw);
        let participation_id = sui::bcs::peel_u64(&mut participation_id_bcs);
        participation_id
    }

    public(package) fun set_participation_id(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, participation_id: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&participation_id);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"participation_id", value, ctx);
    }

    public fun get_battle_instance_id(user_storage: &UserStorage, match_id: u64, agent_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let battle_instance_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"battle_instance_id");
        let mut battle_instance_id_bcs = sui::bcs::new(battle_instance_id_raw);
        let battle_instance_id = sui::bcs::peel_u64(&mut battle_instance_id_bcs);
        battle_instance_id
    }

    public(package) fun set_battle_instance_id(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, battle_instance_id: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&battle_instance_id);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"battle_instance_id", value, ctx);
    }

    public fun get_team(user_storage: &UserStorage, match_id: u64, agent_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let team_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"team");
        let mut team_bcs = sui::bcs::new(team_raw);
        let team = sui::bcs::peel_u8(&mut team_bcs);
        team
    }

    public(package) fun set_team(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, team: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&team);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"team", value, ctx);
    }

    public fun get_placement(user_storage: &UserStorage, match_id: u64, agent_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let placement_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"placement");
        let mut placement_bcs = sui::bcs::new(placement_raw);
        let placement = sui::bcs::peel_u8(&mut placement_bcs);
        placement
    }

    public(package) fun set_placement(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, placement: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&placement);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"placement", value, ctx);
    }

    public fun get(user_storage: &UserStorage, match_id: u64, agent_id: u64): (u64, u64, u8, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let participation_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"participation_id");
        let mut participation_id_bcs = sui::bcs::new(participation_id_raw);
        let participation_id = sui::bcs::peel_u64(&mut participation_id_bcs);
        let battle_instance_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"battle_instance_id");
        let mut battle_instance_id_bcs = sui::bcs::new(battle_instance_id_raw);
        let battle_instance_id = sui::bcs::peel_u64(&mut battle_instance_id_bcs);
        let team_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"team");
        let mut team_bcs = sui::bcs::new(team_raw);
        let team = sui::bcs::peel_u8(&mut team_bcs);
        let placement_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"placement");
        let mut placement_bcs = sui::bcs::new(placement_raw);
        let placement = sui::bcs::peel_u8(&mut placement_bcs);
        (participation_id, battle_instance_id, team, placement)
    }

    public(package) fun set(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, participation_id: u64, battle_instance_id: u64, team: u8, placement: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"participation_id", b"battle_instance_id", b"team", b"placement"];
        let value_tuple = encode(participation_id, battle_instance_id, team, placement);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, match_id: u64, agent_id: u64): MatchParticipation {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let participation_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"participation_id");
        let mut participation_id_bcs = sui::bcs::new(participation_id_raw);
        let participation_id = sui::bcs::peel_u64(&mut participation_id_bcs);
        let battle_instance_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"battle_instance_id");
        let mut battle_instance_id_bcs = sui::bcs::new(battle_instance_id_raw);
        let battle_instance_id = sui::bcs::peel_u64(&mut battle_instance_id_bcs);
        let team_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"team");
        let mut team_bcs = sui::bcs::new(team_raw);
        let team = sui::bcs::peel_u8(&mut team_bcs);
        let placement_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"placement");
        let mut placement_bcs = sui::bcs::new(placement_raw);
        let placement = sui::bcs::peel_u8(&mut placement_bcs);
        MatchParticipation { participation_id, battle_instance_id, team, placement }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, match_participation: MatchParticipation, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"participation_id", b"battle_instance_id", b"team", b"placement"];
        let value_tuple = encode_struct(match_participation);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(participation_id: u64, battle_instance_id: u64, team: u8, placement: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&participation_id));
        value_tuple.push_back(to_bytes(&battle_instance_id));
        value_tuple.push_back(to_bytes(&team));
        value_tuple.push_back(to_bytes(&placement));
        value_tuple
    }

    public fun encode_struct(match_participation: MatchParticipation): vector<vector<u8>> {
        encode(match_participation.participation_id, match_participation.battle_instance_id, match_participation.team, match_participation.placement)
    }

    public fun decode(data: vector<u8>): MatchParticipation {
        let mut bcs_type = sui::bcs::new(data);
        let participation_id = sui::bcs::peel_u64(&mut bcs_type);
        let battle_instance_id = sui::bcs::peel_u64(&mut bcs_type);
        let team = sui::bcs::peel_u8(&mut bcs_type);
        let placement = sui::bcs::peel_u8(&mut bcs_type);
        MatchParticipation {
            participation_id,
            battle_instance_id,
            team,
            placement,
        }
    }
}