// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::match_record {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use numeron::dapp_key;
    use numeron::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"match_record";
    const OFFCHAIN: bool = false;

    public struct MatchRecord has copy, drop, store {
        season_id: u64,
        result: u8,
        round: u32,
        score: u64,
        started_at_ms: u64,
        ended_at_ms: u64,
    }

    public fun new(season_id: u64, result: u8, round: u32, score: u64, started_at_ms: u64, ended_at_ms: u64): MatchRecord {
        MatchRecord {
            season_id,
            result,
            round,
            score,
            started_at_ms,
            ended_at_ms,
        }
    }

    public fun season_id(self: &MatchRecord): u64 {
        self.season_id
    }

    public fun result(self: &MatchRecord): u8 {
        self.result
    }

    public fun round(self: &MatchRecord): u32 {
        self.round
    }

    public fun score(self: &MatchRecord): u64 {
        self.score
    }

    public fun started_at_ms(self: &MatchRecord): u64 {
        self.started_at_ms
    }

    public fun ended_at_ms(self: &MatchRecord): u64 {
        self.ended_at_ms
    }

    public fun update_season_id(self: &mut MatchRecord, season_id: u64) {
        self.season_id = season_id
    }

    public fun update_result(self: &mut MatchRecord, result: u8) {
        self.result = result
    }

    public fun update_round(self: &mut MatchRecord, round: u32) {
        self.round = round
    }

    public fun update_score(self: &mut MatchRecord, score: u64) {
        self.score = score
    }

    public fun update_started_at_ms(self: &mut MatchRecord, started_at_ms: u64) {
        self.started_at_ms = started_at_ms
    }

    public fun update_ended_at_ms(self: &mut MatchRecord, ended_at_ms: u64) {
        self.ended_at_ms = ended_at_ms
    }

    public fun has(user_storage: &UserStorage, match_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, match_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, match_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, match_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"season_id", b"result", b"round", b"score", b"started_at_ms", b"ended_at_ms"], ctx);
    }

    public fun get_season_id(user_storage: &UserStorage, match_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let season_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"season_id");
        let mut season_id_bcs = sui::bcs::new(season_id_raw);
        let season_id = sui::bcs::peel_u64(&mut season_id_bcs);
        season_id
    }

    public(package) fun set_season_id(user_storage: &mut UserStorage, match_id: u64, season_id: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&season_id);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"season_id", value, ctx);
    }

    public fun get_result(user_storage: &UserStorage, match_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let result_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"result");
        let mut result_bcs = sui::bcs::new(result_raw);
        let result = sui::bcs::peel_u8(&mut result_bcs);
        result
    }

    public(package) fun set_result(user_storage: &mut UserStorage, match_id: u64, result: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&result);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"result", value, ctx);
    }

    public fun get_round(user_storage: &UserStorage, match_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let round_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"round");
        let mut round_bcs = sui::bcs::new(round_raw);
        let round = sui::bcs::peel_u32(&mut round_bcs);
        round
    }

    public(package) fun set_round(user_storage: &mut UserStorage, match_id: u64, round: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&round);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"round", value, ctx);
    }

    public fun get_score(user_storage: &UserStorage, match_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let score_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"score");
        let mut score_bcs = sui::bcs::new(score_raw);
        let score = sui::bcs::peel_u64(&mut score_bcs);
        score
    }

    public(package) fun set_score(user_storage: &mut UserStorage, match_id: u64, score: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&score);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"score", value, ctx);
    }

    public fun get_started_at_ms(user_storage: &UserStorage, match_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let started_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"started_at_ms");
        let mut started_at_ms_bcs = sui::bcs::new(started_at_ms_raw);
        let started_at_ms = sui::bcs::peel_u64(&mut started_at_ms_bcs);
        started_at_ms
    }

    public(package) fun set_started_at_ms(user_storage: &mut UserStorage, match_id: u64, started_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&started_at_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"started_at_ms", value, ctx);
    }

    public fun get_ended_at_ms(user_storage: &UserStorage, match_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let ended_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"ended_at_ms");
        let mut ended_at_ms_bcs = sui::bcs::new(ended_at_ms_raw);
        let ended_at_ms = sui::bcs::peel_u64(&mut ended_at_ms_bcs);
        ended_at_ms
    }

    public(package) fun set_ended_at_ms(user_storage: &mut UserStorage, match_id: u64, ended_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&ended_at_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"ended_at_ms", value, ctx);
    }

    public fun get(user_storage: &UserStorage, match_id: u64): (u64, u8, u32, u64, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let season_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"season_id");
        let mut season_id_bcs = sui::bcs::new(season_id_raw);
        let season_id = sui::bcs::peel_u64(&mut season_id_bcs);
        let result_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"result");
        let mut result_bcs = sui::bcs::new(result_raw);
        let result = sui::bcs::peel_u8(&mut result_bcs);
        let round_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"round");
        let mut round_bcs = sui::bcs::new(round_raw);
        let round = sui::bcs::peel_u32(&mut round_bcs);
        let score_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"score");
        let mut score_bcs = sui::bcs::new(score_raw);
        let score = sui::bcs::peel_u64(&mut score_bcs);
        let started_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"started_at_ms");
        let mut started_at_ms_bcs = sui::bcs::new(started_at_ms_raw);
        let started_at_ms = sui::bcs::peel_u64(&mut started_at_ms_bcs);
        let ended_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"ended_at_ms");
        let mut ended_at_ms_bcs = sui::bcs::new(ended_at_ms_raw);
        let ended_at_ms = sui::bcs::peel_u64(&mut ended_at_ms_bcs);
        (season_id, result, round, score, started_at_ms, ended_at_ms)
    }

    public(package) fun set(user_storage: &mut UserStorage, match_id: u64, season_id: u64, result: u8, round: u32, score: u64, started_at_ms: u64, ended_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let field_names = vector[b"season_id", b"result", b"round", b"score", b"started_at_ms", b"ended_at_ms"];
        let value_tuple = encode(season_id, result, round, score, started_at_ms, ended_at_ms);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, match_id: u64): MatchRecord {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let season_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"season_id");
        let mut season_id_bcs = sui::bcs::new(season_id_raw);
        let season_id = sui::bcs::peel_u64(&mut season_id_bcs);
        let result_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"result");
        let mut result_bcs = sui::bcs::new(result_raw);
        let result = sui::bcs::peel_u8(&mut result_bcs);
        let round_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"round");
        let mut round_bcs = sui::bcs::new(round_raw);
        let round = sui::bcs::peel_u32(&mut round_bcs);
        let score_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"score");
        let mut score_bcs = sui::bcs::new(score_raw);
        let score = sui::bcs::peel_u64(&mut score_bcs);
        let started_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"started_at_ms");
        let mut started_at_ms_bcs = sui::bcs::new(started_at_ms_raw);
        let started_at_ms = sui::bcs::peel_u64(&mut started_at_ms_bcs);
        let ended_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"ended_at_ms");
        let mut ended_at_ms_bcs = sui::bcs::new(ended_at_ms_raw);
        let ended_at_ms = sui::bcs::peel_u64(&mut ended_at_ms_bcs);
        MatchRecord { season_id, result, round, score, started_at_ms, ended_at_ms }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, match_id: u64, match_record: MatchRecord, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let field_names = vector[b"season_id", b"result", b"round", b"score", b"started_at_ms", b"ended_at_ms"];
        let value_tuple = encode_struct(match_record);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(season_id: u64, result: u8, round: u32, score: u64, started_at_ms: u64, ended_at_ms: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&season_id));
        value_tuple.push_back(to_bytes(&result));
        value_tuple.push_back(to_bytes(&round));
        value_tuple.push_back(to_bytes(&score));
        value_tuple.push_back(to_bytes(&started_at_ms));
        value_tuple.push_back(to_bytes(&ended_at_ms));
        value_tuple
    }

    public fun encode_struct(match_record: MatchRecord): vector<vector<u8>> {
        encode(match_record.season_id, match_record.result, match_record.round, match_record.score, match_record.started_at_ms, match_record.ended_at_ms)
    }

    public fun decode(data: vector<u8>): MatchRecord {
        let mut bcs_type = sui::bcs::new(data);
        let season_id = sui::bcs::peel_u64(&mut bcs_type);
        let result = sui::bcs::peel_u8(&mut bcs_type);
        let round = sui::bcs::peel_u32(&mut bcs_type);
        let score = sui::bcs::peel_u64(&mut bcs_type);
        let started_at_ms = sui::bcs::peel_u64(&mut bcs_type);
        let ended_at_ms = sui::bcs::peel_u64(&mut bcs_type);
        MatchRecord {
            season_id,
            result,
            round,
            score,
            started_at_ms,
            ended_at_ms,
        }
    }
}