// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::replay_anchor {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use numeron::dapp_key;
    use numeron::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"replay_anchor";
    const OFFCHAIN: bool = false;

    public struct ReplayAnchor has copy, drop, store {
        walrus_blob_epoch: u64,
        replay_digest_hi: u128,
        replay_digest_lo: u128,
    }

    public fun new(walrus_blob_epoch: u64, replay_digest_hi: u128, replay_digest_lo: u128): ReplayAnchor {
        ReplayAnchor {
            walrus_blob_epoch,
            replay_digest_hi,
            replay_digest_lo,
        }
    }

    public fun walrus_blob_epoch(self: &ReplayAnchor): u64 {
        self.walrus_blob_epoch
    }

    public fun replay_digest_hi(self: &ReplayAnchor): u128 {
        self.replay_digest_hi
    }

    public fun replay_digest_lo(self: &ReplayAnchor): u128 {
        self.replay_digest_lo
    }

    public fun update_walrus_blob_epoch(self: &mut ReplayAnchor, walrus_blob_epoch: u64) {
        self.walrus_blob_epoch = walrus_blob_epoch
    }

    public fun update_replay_digest_hi(self: &mut ReplayAnchor, replay_digest_hi: u128) {
        self.replay_digest_hi = replay_digest_hi
    }

    public fun update_replay_digest_lo(self: &mut ReplayAnchor, replay_digest_lo: u128) {
        self.replay_digest_lo = replay_digest_lo
    }

    public fun has(user_storage: &UserStorage, match_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, match_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, match_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, match_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"walrus_blob_epoch", b"replay_digest_hi", b"replay_digest_lo"], ctx);
    }

    public fun get_walrus_blob_epoch(user_storage: &UserStorage, match_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let walrus_blob_epoch_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"walrus_blob_epoch");
        let mut walrus_blob_epoch_bcs = sui::bcs::new(walrus_blob_epoch_raw);
        let walrus_blob_epoch = sui::bcs::peel_u64(&mut walrus_blob_epoch_bcs);
        walrus_blob_epoch
    }

    public(package) fun set_walrus_blob_epoch(user_storage: &mut UserStorage, match_id: u64, walrus_blob_epoch: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&walrus_blob_epoch);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"walrus_blob_epoch", value, ctx);
    }

    public fun get_replay_digest_hi(user_storage: &UserStorage, match_id: u64): u128 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let replay_digest_hi_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"replay_digest_hi");
        let mut replay_digest_hi_bcs = sui::bcs::new(replay_digest_hi_raw);
        let replay_digest_hi = sui::bcs::peel_u128(&mut replay_digest_hi_bcs);
        replay_digest_hi
    }

    public(package) fun set_replay_digest_hi(user_storage: &mut UserStorage, match_id: u64, replay_digest_hi: u128, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&replay_digest_hi);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"replay_digest_hi", value, ctx);
    }

    public fun get_replay_digest_lo(user_storage: &UserStorage, match_id: u64): u128 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let replay_digest_lo_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"replay_digest_lo");
        let mut replay_digest_lo_bcs = sui::bcs::new(replay_digest_lo_raw);
        let replay_digest_lo = sui::bcs::peel_u128(&mut replay_digest_lo_bcs);
        replay_digest_lo
    }

    public(package) fun set_replay_digest_lo(user_storage: &mut UserStorage, match_id: u64, replay_digest_lo: u128, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let value = to_bytes(&replay_digest_lo);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"replay_digest_lo", value, ctx);
    }

    public fun get(user_storage: &UserStorage, match_id: u64): (u64, u128, u128) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let walrus_blob_epoch_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"walrus_blob_epoch");
        let mut walrus_blob_epoch_bcs = sui::bcs::new(walrus_blob_epoch_raw);
        let walrus_blob_epoch = sui::bcs::peel_u64(&mut walrus_blob_epoch_bcs);
        let replay_digest_hi_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"replay_digest_hi");
        let mut replay_digest_hi_bcs = sui::bcs::new(replay_digest_hi_raw);
        let replay_digest_hi = sui::bcs::peel_u128(&mut replay_digest_hi_bcs);
        let replay_digest_lo_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"replay_digest_lo");
        let mut replay_digest_lo_bcs = sui::bcs::new(replay_digest_lo_raw);
        let replay_digest_lo = sui::bcs::peel_u128(&mut replay_digest_lo_bcs);
        (walrus_blob_epoch, replay_digest_hi, replay_digest_lo)
    }

    public(package) fun set(user_storage: &mut UserStorage, match_id: u64, walrus_blob_epoch: u64, replay_digest_hi: u128, replay_digest_lo: u128, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let field_names = vector[b"walrus_blob_epoch", b"replay_digest_hi", b"replay_digest_lo"];
        let value_tuple = encode(walrus_blob_epoch, replay_digest_hi, replay_digest_lo);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, match_id: u64): ReplayAnchor {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let walrus_blob_epoch_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"walrus_blob_epoch");
        let mut walrus_blob_epoch_bcs = sui::bcs::new(walrus_blob_epoch_raw);
        let walrus_blob_epoch = sui::bcs::peel_u64(&mut walrus_blob_epoch_bcs);
        let replay_digest_hi_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"replay_digest_hi");
        let mut replay_digest_hi_bcs = sui::bcs::new(replay_digest_hi_raw);
        let replay_digest_hi = sui::bcs::peel_u128(&mut replay_digest_hi_bcs);
        let replay_digest_lo_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"replay_digest_lo");
        let mut replay_digest_lo_bcs = sui::bcs::new(replay_digest_lo_raw);
        let replay_digest_lo = sui::bcs::peel_u128(&mut replay_digest_lo_bcs);
        ReplayAnchor { walrus_blob_epoch, replay_digest_hi, replay_digest_lo }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, match_id: u64, replay_anchor: ReplayAnchor, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        let field_names = vector[b"walrus_blob_epoch", b"replay_digest_hi", b"replay_digest_lo"];
        let value_tuple = encode_struct(replay_anchor);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(walrus_blob_epoch: u64, replay_digest_hi: u128, replay_digest_lo: u128): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&walrus_blob_epoch));
        value_tuple.push_back(to_bytes(&replay_digest_hi));
        value_tuple.push_back(to_bytes(&replay_digest_lo));
        value_tuple
    }

    public fun encode_struct(replay_anchor: ReplayAnchor): vector<vector<u8>> {
        encode(replay_anchor.walrus_blob_epoch, replay_anchor.replay_digest_hi, replay_anchor.replay_digest_lo)
    }

    public fun decode(data: vector<u8>): ReplayAnchor {
        let mut bcs_type = sui::bcs::new(data);
        let walrus_blob_epoch = sui::bcs::peel_u64(&mut bcs_type);
        let replay_digest_hi = sui::bcs::peel_u128(&mut bcs_type);
        let replay_digest_lo = sui::bcs::peel_u128(&mut bcs_type);
        ReplayAnchor {
            walrus_blob_epoch,
            replay_digest_hi,
            replay_digest_lo,
        }
    }
}