// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::reward_claim {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use numeron::dapp_key;
    use numeron::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"reward_claim";
    const OFFCHAIN: bool = false;

    public struct RewardClaim has copy, drop, store {
        reward_type: u8,
        amount: u64,
        claimed_at_ms: u64,
    }

    public fun new(reward_type: u8, amount: u64, claimed_at_ms: u64): RewardClaim {
        RewardClaim {
            reward_type,
            amount,
            claimed_at_ms,
        }
    }

    public fun reward_type(self: &RewardClaim): u8 {
        self.reward_type
    }

    public fun amount(self: &RewardClaim): u64 {
        self.amount
    }

    public fun claimed_at_ms(self: &RewardClaim): u64 {
        self.claimed_at_ms
    }

    public fun update_reward_type(self: &mut RewardClaim, reward_type: u8) {
        self.reward_type = reward_type
    }

    public fun update_amount(self: &mut RewardClaim, amount: u64) {
        self.amount = amount
    }

    public fun update_claimed_at_ms(self: &mut RewardClaim, claimed_at_ms: u64) {
        self.claimed_at_ms = claimed_at_ms
    }

    public fun has(user_storage: &UserStorage, match_id: u64, agent_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, match_id: u64, agent_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, match_id: u64, agent_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"reward_type", b"amount", b"claimed_at_ms"], ctx);
    }

    public fun get_reward_type(user_storage: &UserStorage, match_id: u64, agent_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let reward_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"reward_type");
        let mut reward_type_bcs = sui::bcs::new(reward_type_raw);
        let reward_type = sui::bcs::peel_u8(&mut reward_type_bcs);
        reward_type
    }

    public(package) fun set_reward_type(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, reward_type: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&reward_type);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"reward_type", value, ctx);
    }

    public fun get_amount(user_storage: &UserStorage, match_id: u64, agent_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let amount_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"amount");
        let mut amount_bcs = sui::bcs::new(amount_raw);
        let amount = sui::bcs::peel_u64(&mut amount_bcs);
        amount
    }

    public(package) fun set_amount(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, amount: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&amount);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"amount", value, ctx);
    }

    public fun get_claimed_at_ms(user_storage: &UserStorage, match_id: u64, agent_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let claimed_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"claimed_at_ms");
        let mut claimed_at_ms_bcs = sui::bcs::new(claimed_at_ms_raw);
        let claimed_at_ms = sui::bcs::peel_u64(&mut claimed_at_ms_bcs);
        claimed_at_ms
    }

    public(package) fun set_claimed_at_ms(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, claimed_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&claimed_at_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"claimed_at_ms", value, ctx);
    }

    public fun get(user_storage: &UserStorage, match_id: u64, agent_id: u64): (u8, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let reward_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"reward_type");
        let mut reward_type_bcs = sui::bcs::new(reward_type_raw);
        let reward_type = sui::bcs::peel_u8(&mut reward_type_bcs);
        let amount_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"amount");
        let mut amount_bcs = sui::bcs::new(amount_raw);
        let amount = sui::bcs::peel_u64(&mut amount_bcs);
        let claimed_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"claimed_at_ms");
        let mut claimed_at_ms_bcs = sui::bcs::new(claimed_at_ms_raw);
        let claimed_at_ms = sui::bcs::peel_u64(&mut claimed_at_ms_bcs);
        (reward_type, amount, claimed_at_ms)
    }

    public(package) fun set(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, reward_type: u8, amount: u64, claimed_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"reward_type", b"amount", b"claimed_at_ms"];
        let value_tuple = encode(reward_type, amount, claimed_at_ms);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, match_id: u64, agent_id: u64): RewardClaim {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let reward_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"reward_type");
        let mut reward_type_bcs = sui::bcs::new(reward_type_raw);
        let reward_type = sui::bcs::peel_u8(&mut reward_type_bcs);
        let amount_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"amount");
        let mut amount_bcs = sui::bcs::new(amount_raw);
        let amount = sui::bcs::peel_u64(&mut amount_bcs);
        let claimed_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"claimed_at_ms");
        let mut claimed_at_ms_bcs = sui::bcs::new(claimed_at_ms_raw);
        let claimed_at_ms = sui::bcs::peel_u64(&mut claimed_at_ms_bcs);
        RewardClaim { reward_type, amount, claimed_at_ms }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, match_id: u64, agent_id: u64, reward_claim: RewardClaim, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&match_id));
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"reward_type", b"amount", b"claimed_at_ms"];
        let value_tuple = encode_struct(reward_claim);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(reward_type: u8, amount: u64, claimed_at_ms: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&reward_type));
        value_tuple.push_back(to_bytes(&amount));
        value_tuple.push_back(to_bytes(&claimed_at_ms));
        value_tuple
    }

    public fun encode_struct(reward_claim: RewardClaim): vector<vector<u8>> {
        encode(reward_claim.reward_type, reward_claim.amount, reward_claim.claimed_at_ms)
    }

    public fun decode(data: vector<u8>): RewardClaim {
        let mut bcs_type = sui::bcs::new(data);
        let reward_type = sui::bcs::peel_u8(&mut bcs_type);
        let amount = sui::bcs::peel_u64(&mut bcs_type);
        let claimed_at_ms = sui::bcs::peel_u64(&mut bcs_type);
        RewardClaim {
            reward_type,
            amount,
            claimed_at_ms,
        }
    }
}