// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::season_config {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use numeron::dapp_key;
    use numeron::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"season_config";
    const OFFCHAIN: bool = false;

    public struct SeasonConfig has copy, drop, store {
        ruleset_version: u32,
        start_at_ms: u64,
        end_at_ms: u64,
        active: bool,
    }

    public fun new(ruleset_version: u32, start_at_ms: u64, end_at_ms: u64, active: bool): SeasonConfig {
        SeasonConfig {
            ruleset_version,
            start_at_ms,
            end_at_ms,
            active,
        }
    }

    public fun ruleset_version(self: &SeasonConfig): u32 {
        self.ruleset_version
    }

    public fun start_at_ms(self: &SeasonConfig): u64 {
        self.start_at_ms
    }

    public fun end_at_ms(self: &SeasonConfig): u64 {
        self.end_at_ms
    }

    public fun active(self: &SeasonConfig): bool {
        self.active
    }

    public fun update_ruleset_version(self: &mut SeasonConfig, ruleset_version: u32) {
        self.ruleset_version = ruleset_version
    }

    public fun update_start_at_ms(self: &mut SeasonConfig, start_at_ms: u64) {
        self.start_at_ms = start_at_ms
    }

    public fun update_end_at_ms(self: &mut SeasonConfig, end_at_ms: u64) {
        self.end_at_ms = end_at_ms
    }

    public fun update_active(self: &mut SeasonConfig, active: bool) {
        self.active = active
    }

    public fun has(user_storage: &UserStorage, season_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, season_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, season_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, season_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"ruleset_version", b"start_at_ms", b"end_at_ms", b"active"], ctx);
    }

    public fun get_ruleset_version(user_storage: &UserStorage, season_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let ruleset_version_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"ruleset_version");
        let mut ruleset_version_bcs = sui::bcs::new(ruleset_version_raw);
        let ruleset_version = sui::bcs::peel_u32(&mut ruleset_version_bcs);
        ruleset_version
    }

    public(package) fun set_ruleset_version(user_storage: &mut UserStorage, season_id: u64, ruleset_version: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let value = to_bytes(&ruleset_version);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"ruleset_version", value, ctx);
    }

    public fun get_start_at_ms(user_storage: &UserStorage, season_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let start_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"start_at_ms");
        let mut start_at_ms_bcs = sui::bcs::new(start_at_ms_raw);
        let start_at_ms = sui::bcs::peel_u64(&mut start_at_ms_bcs);
        start_at_ms
    }

    public(package) fun set_start_at_ms(user_storage: &mut UserStorage, season_id: u64, start_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let value = to_bytes(&start_at_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"start_at_ms", value, ctx);
    }

    public fun get_end_at_ms(user_storage: &UserStorage, season_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let end_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"end_at_ms");
        let mut end_at_ms_bcs = sui::bcs::new(end_at_ms_raw);
        let end_at_ms = sui::bcs::peel_u64(&mut end_at_ms_bcs);
        end_at_ms
    }

    public(package) fun set_end_at_ms(user_storage: &mut UserStorage, season_id: u64, end_at_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let value = to_bytes(&end_at_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"end_at_ms", value, ctx);
    }

    public fun get_active(user_storage: &UserStorage, season_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let active_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"active");
        let mut active_bcs = sui::bcs::new(active_raw);
        let active = sui::bcs::peel_bool(&mut active_bcs);
        active
    }

    public(package) fun set_active(user_storage: &mut UserStorage, season_id: u64, active: bool, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let value = to_bytes(&active);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"active", value, ctx);
    }

    public fun get(user_storage: &UserStorage, season_id: u64): (u32, u64, u64, bool) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let ruleset_version_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"ruleset_version");
        let mut ruleset_version_bcs = sui::bcs::new(ruleset_version_raw);
        let ruleset_version = sui::bcs::peel_u32(&mut ruleset_version_bcs);
        let start_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"start_at_ms");
        let mut start_at_ms_bcs = sui::bcs::new(start_at_ms_raw);
        let start_at_ms = sui::bcs::peel_u64(&mut start_at_ms_bcs);
        let end_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"end_at_ms");
        let mut end_at_ms_bcs = sui::bcs::new(end_at_ms_raw);
        let end_at_ms = sui::bcs::peel_u64(&mut end_at_ms_bcs);
        let active_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"active");
        let mut active_bcs = sui::bcs::new(active_raw);
        let active = sui::bcs::peel_bool(&mut active_bcs);
        (ruleset_version, start_at_ms, end_at_ms, active)
    }

    public(package) fun set(user_storage: &mut UserStorage, season_id: u64, ruleset_version: u32, start_at_ms: u64, end_at_ms: u64, active: bool, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let field_names = vector[b"ruleset_version", b"start_at_ms", b"end_at_ms", b"active"];
        let value_tuple = encode(ruleset_version, start_at_ms, end_at_ms, active);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, season_id: u64): SeasonConfig {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let ruleset_version_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"ruleset_version");
        let mut ruleset_version_bcs = sui::bcs::new(ruleset_version_raw);
        let ruleset_version = sui::bcs::peel_u32(&mut ruleset_version_bcs);
        let start_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"start_at_ms");
        let mut start_at_ms_bcs = sui::bcs::new(start_at_ms_raw);
        let start_at_ms = sui::bcs::peel_u64(&mut start_at_ms_bcs);
        let end_at_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"end_at_ms");
        let mut end_at_ms_bcs = sui::bcs::new(end_at_ms_raw);
        let end_at_ms = sui::bcs::peel_u64(&mut end_at_ms_bcs);
        let active_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"active");
        let mut active_bcs = sui::bcs::new(active_raw);
        let active = sui::bcs::peel_bool(&mut active_bcs);
        SeasonConfig { ruleset_version, start_at_ms, end_at_ms, active }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, season_id: u64, season_config: SeasonConfig, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season_id));
        let field_names = vector[b"ruleset_version", b"start_at_ms", b"end_at_ms", b"active"];
        let value_tuple = encode_struct(season_config);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(ruleset_version: u32, start_at_ms: u64, end_at_ms: u64, active: bool): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&ruleset_version));
        value_tuple.push_back(to_bytes(&start_at_ms));
        value_tuple.push_back(to_bytes(&end_at_ms));
        value_tuple.push_back(to_bytes(&active));
        value_tuple
    }

    public fun encode_struct(season_config: SeasonConfig): vector<vector<u8>> {
        encode(season_config.ruleset_version, season_config.start_at_ms, season_config.end_at_ms, season_config.active)
    }

    public fun decode(data: vector<u8>): SeasonConfig {
        let mut bcs_type = sui::bcs::new(data);
        let ruleset_version = sui::bcs::peel_u32(&mut bcs_type);
        let start_at_ms = sui::bcs::peel_u64(&mut bcs_type);
        let end_at_ms = sui::bcs::peel_u64(&mut bcs_type);
        let active = sui::bcs::peel_bool(&mut bcs_type);
        SeasonConfig {
            ruleset_version,
            start_at_ms,
            end_at_ms,
            active,
        }
    }
}