// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::user_storage_init {
  use dubhe::dapp_service::{DappHub, DappStorage};
  use dubhe::dapp_system;
  use numeron::dapp_key::DappKey;

  /// Create a UserStorage for the transaction sender within this DApp.
  /// Must be called once before the user can interact with any user-level resources.
  /// Aborts if the DApp is currently suspended or the framework version has advanced.
  #[allow(lint(public_entry))]
  public entry fun init_user_storage(
      dapp_hub: &DappHub,
      dapp_storage: &mut DappStorage,
      ctx: &mut TxContext,
  ) {
      dapp_system::create_user_storage<DappKey>(dapp_hub, dapp_storage, ctx);
  }
}
