// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module numeron::deploy_hook {
    use dubhe::dapp_service::DappStorage;

    public(package) fun run(_dapp_storage: &mut DappStorage, _ctx: &mut TxContext) {
        // Initialise any DappStorage-level defaults here.
    }
}