  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::connection_point {

  use std::ascii::String;

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::region_type::RegionType;

  use numeron::connection_type::ConnectionType;

  public struct ConnectionPoint has copy, drop, store {
    position: Position,
    connected_position: Position,
  }

  public fun new(position: Position, connected_position: Position): ConnectionPoint {
    ConnectionPoint {
                                   position,connected_position
                               }
  }

  public fun get(self: &ConnectionPoint): (Position,Position) {
    (self.position,self.connected_position)
  }

  public fun get_position(self: &ConnectionPoint): Position {
    self.position
  }

  public fun get_connected_position(self: &ConnectionPoint): Position {
    self.connected_position
  }

  public(package) fun set_position(self: &mut ConnectionPoint, position: Position) {
    self.position = position;
  }

  public(package) fun set_connected_position(self: &mut ConnectionPoint, connected_position: Position) {
    self.connected_position = connected_position;
  }

  public(package) fun set(self: &mut ConnectionPoint, position: Position, connected_position: Position) {
    self.position = position;
    self.connected_position = connected_position;
  }
}
