  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::connection_type {

  public enum ConnectionType has copy, drop , store {
                                Bridge,Custom,Gate,Path,Portal
                        }

  public fun new_bridge(): ConnectionType {
    ConnectionType::Bridge
  }

  public fun new_custom(): ConnectionType {
    ConnectionType::Custom
  }

  public fun new_gate(): ConnectionType {
    ConnectionType::Gate
  }

  public fun new_path(): ConnectionType {
    ConnectionType::Path
  }

  public fun new_portal(): ConnectionType {
    ConnectionType::Portal
  }
}
