  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::creature_type {

  public enum CreatureType has copy, drop , store {
                                Dark,Earth,Fire,Light,None,Water,Wind
                        }

  public fun new_dark(): CreatureType {
    CreatureType::Dark
  }

  public fun new_earth(): CreatureType {
    CreatureType::Earth
  }

  public fun new_fire(): CreatureType {
    CreatureType::Fire
  }

  public fun new_light(): CreatureType {
    CreatureType::Light
  }

  public fun new_none(): CreatureType {
    CreatureType::None
  }

  public fun new_water(): CreatureType {
    CreatureType::Water
  }

  public fun new_wind(): CreatureType {
    CreatureType::Wind
  }
}
