  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::creature_spawned_event {

  use sui::event;

  use std::ascii::String;

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::position::Position;

  use numeron::creature_stats::CreatureStats;

  use numeron::map_config::MapConfig;

  use numeron::extension_data::ExtensionData;

  public struct CreatureSpawnedEvent has copy, drop {
    creature_id: address,
    creature_type: CreatureType,
    position: Position,
  }

  public fun new(creature_id: address, creature_type: CreatureType, position: Position): CreatureSpawnedEvent {
    CreatureSpawnedEvent {
                                   creature_id,creature_type,position
                               }
  }
}
