  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::map_created {

  use std::ascii::String;

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::region_type::RegionType;

  use numeron::connection_type::ConnectionType;

  public struct MapCreated has copy, drop, store {
    map_id: address,
    creator: address,
    config: MapConfig,
  }

  public fun new(map_id: address, creator: address, config: MapConfig): MapCreated {
    MapCreated {
                                   map_id,creator,config
                               }
  }

  public fun get(self: &MapCreated): (address,address,MapConfig) {
    (self.map_id,self.creator,self.config)
  }

  public fun get_map_id(self: &MapCreated): address {
    self.map_id
  }

  public fun get_creator(self: &MapCreated): address {
    self.creator
  }

  public fun get_config(self: &MapCreated): MapConfig {
    self.config
  }

  public(package) fun set_map_id(self: &mut MapCreated, map_id: address) {
    self.map_id = map_id;
  }

  public(package) fun set_creator(self: &mut MapCreated, creator: address) {
    self.creator = creator;
  }

  public(package) fun set_config(self: &mut MapCreated, config: MapConfig) {
    self.config = config;
  }

  public(package) fun set(self: &mut MapCreated, map_id: address, creator: address, config: MapConfig) {
    self.map_id = map_id;
    self.creator = creator;
    self.config = config;
  }
}
