  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::map_config {

  use std::ascii::String;

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::position::Position;

  public struct MapConfig has copy, drop, store {
    width: u64,
    height: u64,
    creator: address,
    terrain: vector<vector<TerrainType>>,
    spawn_points: vector<Position>,
  }

  public fun new(
    width: u64,
    height: u64,
    creator: address,
    terrain: vector<vector<TerrainType>>,
    spawn_points: vector<Position>,
  ): MapConfig {
    MapConfig {
                                   width,height,creator,terrain,spawn_points
                               }
  }

  public fun get(self: &MapConfig): (u64,u64,address,vector<vector<TerrainType>>,vector<Position>) {
    (self.width,self.height,self.creator,self.terrain,self.spawn_points)
  }

  public fun get_width(self: &MapConfig): u64 {
    self.width
  }

  public fun get_height(self: &MapConfig): u64 {
    self.height
  }

  public fun get_creator(self: &MapConfig): address {
    self.creator
  }

  public fun get_terrain(self: &MapConfig): vector<vector<TerrainType>> {
    self.terrain
  }

  public fun get_spawn_points(self: &MapConfig): vector<Position> {
    self.spawn_points
  }

  public(package) fun set_width(self: &mut MapConfig, width: u64) {
    self.width = width;
  }

  public(package) fun set_height(self: &mut MapConfig, height: u64) {
    self.height = height;
  }

  public(package) fun set_creator(self: &mut MapConfig, creator: address) {
    self.creator = creator;
  }

  public(package) fun set_terrain(self: &mut MapConfig, terrain: vector<vector<TerrainType>>) {
    self.terrain = terrain;
  }

  public(package) fun set_spawn_points(self: &mut MapConfig, spawn_points: vector<Position>) {
    self.spawn_points = spawn_points;
  }

  public(package) fun set(
    self: &mut MapConfig,
    width: u64,
    height: u64,
    creator: address,
    terrain: vector<vector<TerrainType>>,
    spawn_points: vector<Position>,
  ) {
    self.width = width;
    self.height = height;
    self.creator = creator;
    self.terrain = terrain;
    self.spawn_points = spawn_points;
  }
}
