  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::map_created_event {

  use sui::event;

  use std::ascii::String;

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::position::Position;

  use numeron::creature_stats::CreatureStats;

  use numeron::map_config::MapConfig;

  use numeron::extension_data::ExtensionData;

  public struct MapCreatedEvent has copy, drop {
    map_id: address,
    creator: address,
    config: MapConfig,
  }

  public fun new(map_id: address, creator: address, config: MapConfig): MapCreatedEvent {
    MapCreatedEvent {
                                   map_id,creator,config
                               }
  }
}
