  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::position {

  use std::ascii::String;

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::region_type::RegionType;

  use numeron::connection_type::ConnectionType;

  public struct Position has copy, drop, store {
    x: u64,
    y: u64,
    layer: u8,
  }

  public fun new(x: u64, y: u64, layer: u8): Position {
    Position {
                                   x,y,layer
                               }
  }

  public fun get(self: &Position): (u64,u64,u8) {
    (self.x,self.y,self.layer)
  }

  public fun get_x(self: &Position): u64 {
    self.x
  }

  public fun get_y(self: &Position): u64 {
    self.y
  }

  public fun get_layer(self: &Position): u8 {
    self.layer
  }

  public(package) fun set_x(self: &mut Position, x: u64) {
    self.x = x;
  }

  public(package) fun set_y(self: &mut Position, y: u64) {
    self.y = y;
  }

  public(package) fun set_layer(self: &mut Position, layer: u8) {
    self.layer = layer;
  }

  public(package) fun set(self: &mut Position, x: u64, y: u64, layer: u8) {
    self.x = x;
    self.y = y;
    self.layer = layer;
  }
}
