  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::region_metadata {

  use std::ascii::String;

  use numeron::creature_type::CreatureType;

  use numeron::rarity::Rarity;

  use numeron::terrain_type::TerrainType;

  use numeron::battle_result::BattleResult;

  use numeron::weather_type::WeatherType;

  use numeron::region_type::RegionType;

  use numeron::connection_type::ConnectionType;

  public struct RegionMetadata has copy, drop, store {
    name: String,
    description: String,
    version: u64,
    tags: vector<String>,
    custom_data: vector<u8>,
  }

  public fun new(
    name: String,
    description: String,
    version: u64,
    tags: vector<String>,
    custom_data: vector<u8>,
  ): RegionMetadata {
    RegionMetadata {
                                   name,description,version,tags,custom_data
                               }
  }

  public fun get(self: &RegionMetadata): (String,String,u64,vector<String>,vector<u8>) {
    (self.name,self.description,self.version,self.tags,self.custom_data)
  }

  public fun get_name(self: &RegionMetadata): String {
    self.name
  }

  public fun get_description(self: &RegionMetadata): String {
    self.description
  }

  public fun get_version(self: &RegionMetadata): u64 {
    self.version
  }

  public fun get_tags(self: &RegionMetadata): vector<String> {
    self.tags
  }

  public fun get_custom_data(self: &RegionMetadata): vector<u8> {
    self.custom_data
  }

  public(package) fun set_name(self: &mut RegionMetadata, name: String) {
    self.name = name;
  }

  public(package) fun set_description(self: &mut RegionMetadata, description: String) {
    self.description = description;
  }

  public(package) fun set_version(self: &mut RegionMetadata, version: u64) {
    self.version = version;
  }

  public(package) fun set_tags(self: &mut RegionMetadata, tags: vector<String>) {
    self.tags = tags;
  }

  public(package) fun set_custom_data(self: &mut RegionMetadata, custom_data: vector<u8>) {
    self.custom_data = custom_data;
  }

  public(package) fun set(
    self: &mut RegionMetadata,
    name: String,
    description: String,
    version: u64,
    tags: vector<String>,
    custom_data: vector<u8>,
  ) {
    self.name = name;
    self.description = description;
    self.version = version;
    self.tags = tags;
    self.custom_data = custom_data;
  }
}
