  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::region_type {

  public enum RegionType has copy, drop , store {
                                Custom,Dungeon,Gym,Special,Town,Wild
                        }

  public fun new_custom(): RegionType {
    RegionType::Custom
  }

  public fun new_dungeon(): RegionType {
    RegionType::Dungeon
  }

  public fun new_gym(): RegionType {
    RegionType::Gym
  }

  public fun new_special(): RegionType {
    RegionType::Special
  }

  public fun new_town(): RegionType {
    RegionType::Town
  }

  public fun new_wild(): RegionType {
    RegionType::Wild
  }
}
