  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::terrain_type {

  public enum TerrainType has copy, drop , store {
                                Cave,Forest,Lake,Mountain,Plain,Volcano
                        }

  public fun new_cave(): TerrainType {
    TerrainType::Cave
  }

  public fun new_forest(): TerrainType {
    TerrainType::Forest
  }

  public fun new_lake(): TerrainType {
    TerrainType::Lake
  }

  public fun new_mountain(): TerrainType {
    TerrainType::Mountain
  }

  public fun new_plain(): TerrainType {
    TerrainType::Plain
  }

  public fun new_volcano(): TerrainType {
    TerrainType::Volcano
  }
}
