  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::weather_type {

  public enum WeatherType has copy, drop , store {
                                Clear,Foggy,Rain,Storm,Sunny
                        }

  public fun new_clear(): WeatherType {
    WeatherType::Clear
  }

  public fun new_foggy(): WeatherType {
    WeatherType::Foggy
  }

  public fun new_rain(): WeatherType {
    WeatherType::Rain
  }

  public fun new_storm(): WeatherType {
    WeatherType::Storm
  }

  public fun new_sunny(): WeatherType {
    WeatherType::Sunny
  }
}
