  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::weather_type {

  public enum WeatherType has copy, drop , store {
                                Clear,Cloudy,Custom,Fog,Rain,Snow,Storm,Sandstorm,Sunny
                        }

  public fun new_clear(): WeatherType {
    WeatherType::Clear
  }

  public fun new_cloudy(): WeatherType {
    WeatherType::Cloudy
  }

  public fun new_custom(): WeatherType {
    WeatherType::Custom
  }

  public fun new_fog(): WeatherType {
    WeatherType::Fog
  }

  public fun new_rain(): WeatherType {
    WeatherType::Rain
  }

  public fun new_snow(): WeatherType {
    WeatherType::Snow
  }

  public fun new_storm(): WeatherType {
    WeatherType::Storm
  }

  public fun new_sandstorm(): WeatherType {
    WeatherType::Sandstorm
  }

  public fun new_sunny(): WeatherType {
    WeatherType::Sunny
  }
}
